### ISSUE TITLE
Demo里podFile里面都是引用的本地文件？

### ISSUE THREAD

**Issue by Rain-dew** [LoSenTrad/LSTPopView#12]
没法运行啊

**Comment by LoSenTrad** [comment]
注释掉了呀. 你pod install或者pod update 就行了

**Comment by Rain-dew** [comment]
你pod是什么版本啊




| |
zhangyuluios
|
|
邮箱：zhangyuluios@163.com
|

Signature is customized by Netease Mail Master

在2020年06月24日 14:35，LoSenTrad 写道：

注释掉了呀. 你pod install或者pod update 就行了

**Comment by LoSenTrad** [comment]
@Rain-dew 最新版本是 0.1.06221750 , demo 的podfile 只需  pod 'LSTPopView', :path => '../'
  pod 'Masonry' 这个两个就行了

**Comment by Rain-dew** [comment]
我们两个pod版本不同。我这边是1.5.3，这样会报错




| |
zhangyuluios
|
|
邮箱：zhangyuluios@163.com
|

Signature is customized by Netease Mail Master

在2020年06月24日 15:14，LoSenTrad 写道：

@Rain-dew 最新版本是 0.1.06221750 , demo 的podfile 只需 pod 'LSTPopView', :path => '../'
pod 'Masonry' 这个两个就行了

**Comment by LoSenTrad** [comment]
可以加我qq 490790096 我帮你看一下

**Comment by SwiftHsw** [comment]
打不开！运行不了。，pod 也不行= =

**Comment by LoSenTrad** [comment]
@SwiftHsw pod update 或者pod install之后,打开LSTPopView.xcworkspace
