### ISSUE TITLE
子视图有UITableView的时候点击cell被拦截了

### ISSUE THREAD

**Issue by haochentao** [LoSenTrad/LSTPopView#17]
首先非常喜欢楼主的LSTPopView
以下是我解决点击cell被拦截了的办法、或者楼主是否有更好的
#pragma mark-手势代理，解决和tableview点击发生的冲突
-(BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldReceiveTouch:(UITouch *)touch {
   if ([NSStringFromClass([touch.view class]) isEqualToString:@"UITableViewCellContentView"]) {//判断如果点击的是tableView的cell，就把手势给关闭了
      return NO;//关闭手势
   }//否则手势存在
   return YES;
 }

**Comment by haochentao** [comment]
看到了楼主最新代码是已经注释掉了手势
我还是保留了手势只不过添加了上面一段并且设置了delegate
    customViewLP.delegate = popView;
    customViewTap.delegate = popView;

**Comment by LoSenTrad** [comment]
@haochentao  之前有人提出来相关问题, 以前用过上述的解决方案,还是处理不了collectionView上所产生的问题. 在没有好的方案之前, 点击事件用button替换了, 长按事件暂时关闭.
