### ISSUE TITLE
id obj = popViewArr[popViewArr.count-2];崩溃

### ISSUE THREAD

**Issue by p710041025** [LoSenTrad/LSTPopView#19]
id obj = popViewArr[popViewArr.count-2];
崩溃

**Comment by p710041025** [comment]
[__NSSingleObjectArrayI objectAtIndex:]: index 18446744073709551615 beyond bounds [0 .. 0]'

First throw call stack:
(
	0   CoreFoundation                      0x00007fff23e3de6e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff512539b2 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23d77840 -[__NSSingleObjectArrayI getObjects:range:] + 0
	3   LSTPopView                          0x00000001011b5707 __56-[LSTPopView dismissWithDismissStyle:duration:isRemove:]_block_invoke.237 + 151
	4   libdispatch.dylib                   0x00000001014b0e8e _dispatch_client_callout + 8
	5   libdispatch.dylib                   0x00000001014b37a3 _dispatch_continuation_pop + 552
	6   libdispatch.dylib                   0x00000001014c6b2c _dispatch_source_invoke + 2205
	7   libdispatch.dylib                   0x00000001014bebce _dispatch_main_queue_callback_4CF + 692
	8   CoreFoundation                      0x00007fff23da1869 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	9   CoreFoundation                      0x00007fff23d9c3b9 __CFRunLoopRun + 2041
	10  CoreFoundation                      0x00007fff23d9b8a4 CFRunLoopRunSpecific + 404
	11  GraphicsServices                    0x00007fff38c39bbe GSEventRunModal + 139
	12  UIKitCore                           0x00007fff49325968 UIApplicationMain + 1605
	13  LSTPopView                          0x00000001011a12d0 main + 112
	14  libdyld.dylib                       0x00007fff520ce1fd start + 1
	15  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by LoSenTrad** [comment]
@p710041025 已经处理了 使用最新版本
