### ISSUE TITLE
[!] Unable to find a specification for `LSTTimer` depended upon by `LSTPopView`

### ISSUE THREAD

**Issue by SwiftHsw** [LoSenTrad/LSTPopView#20]
[!] Unable to find a specification for `LSTTimer` depended upon by `LSTPopView`

**Comment by LoSenTrad** [comment]
@SwiftHsw pod update更新

**Comment by SwiftHsw** [comment]
mac@shuaidaobuxing Plant Cognitive Expert % pod install
Analyzing dependencies
Downloading dependencies
Installing LSTCategory (0.2.04281546)
Installing LSTPopView (0.1.08111531)

[!] Error installing LSTPopView
[!] /usr/bin/git clone https://github.com/LoSenTrad/LSTPopView.git /var/folders/tm/fj7rfqrs3t7cmnpmbpbswbs00000gn/T/d20200910-47703-mvl450 --template= --single-branch --depth 1 --branch 0.1.08111531

Cloning into '/var/folders/tm/fj7rfqrs3t7cmnpmbpbswbs00000gn/T/d20200910-47703-mvl450'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by LoSenTrad** [comment]
@SwiftHsw pod update 试试呀

**Comment by SwiftHsw** [comment]
试过了，你的demo 我运行了，可是我其他项目就不行= = 

报错这个 [!] No podspec found for `LSTPopView` in `../`

**Comment by SwiftHsw** [comment]
Update all pods
Updating local specs repositories

CocoaPods 1.10.0.beta.2 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.10.0.beta.2

Analyzing dependencies
[!] No podspec found for `LSTPopView` in `../`

[!] Automatically assigning platform `iOS` with version `9.0` on target `YaoShui Car brand` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
mac@shuaidaobuxing YaoShui Car brand %

**Comment by LoSenTrad** [comment]
@SwiftHsw 加我QQ 交流

**Comment by LoSenTrad** [comment]
@SwiftHsw 进QQ群

**Comment by SwiftHsw** [comment]
好的
