### ISSUE TITLE
弹框展示后如何修改高度（例如点击弹框内一个button，弹框变高）

### ISSUE THREAD

**Issue by H4AER** [LoSenTrad/LSTPopView#22]

**Comment by LoSenTrad** [comment]
直接动态修改自定义view的高度就行了 不清楚的加我QQ或者微信

**Comment by H4AER** [comment]
如果有textField正在编辑中，修改高度，pop会回到初始位置
复现代码
修改 LSTAutoKeyboardVC  中view.addBlock为
 view.addBlock = ^(id sender) {
        wk_view.height += 20;
    };
视频 https://gitee.com/1264788359/pro/raw/master/lstpop.mp4

**Comment by LoSenTrad** [comment]
@H4AER 在本周会发布一个大版本,然后修复这个问题. 感谢反馈

**Comment by LoSenTrad** [comment]
@H4AER 新版本已经优化了这个问题了_

**Comment by H4AER** [comment]
pod 中最新版0.1.08251125 好像没优化这个问题
<img width="747" alt="QQ20201218-142012@2x" src="https://user-images.githubusercontent.com/15047422/102581749-2df7f480-413c-11eb-9b97-46b5f29978da.png">
图片上面的是pod 0.1.08251125 中代码
下面是我在群里下载的

**Comment by LoSenTrad** [comment]
@H4AER 加我一下 新版本已经内测一个星期了  给你内测版本体体验一下
