### ISSUE TITLE
混编项目如何使用

### ISSUE THREAD

**Issue by H4AER** [LoSenTrad/LSTPopView#23]
target has transitive dependencies that include statically linked binaries: (LSTCategory)

**Comment by LoSenTrad** [comment]
@H4AER 新版本会直接更新支持swift项目或者混编项目的支持. 目前暂时解决的办法是手动集成进去. 进群或者加我, 发你手动集成教程和文件.

**Comment by H4AER** [comment]
好的，🌹🌹🌹
