### ISSUE TITLE
pod install 报错

### ISSUE THREAD

**Issue by fmway123** [LoSenTrad/LSTPopView#24]
The 'xxx' target has transitive dependencies that include statically linked binaries: (LSTCategory)

**Comment by LoSenTrad** [comment]
@Joecao123 加群 群里面有临时的手动集成包, 新版本发布就能解决混编或者是swift项目的pod集成问题

**Comment by fmway123** [comment]
@LoSenTrad 好的，多谢!

**Comment by qq826075241** [comment]
@LoSenTrad  群在哪呢？

**Comment by LoSenTrad** [comment]
QQ群:1045568246

**Comment by qq826075241** [comment]
@LoSenTrad 看到了。位置有点隐蔽，建议写在Redme里

**Comment by LoSenTrad** [comment]
好的 好的
