### ISSUE TITLE
背景点击不会收回弹窗,不执行block

### ISSUE THREAD

**Issue by Madness66** [LoSenTrad/LSTPopView#3]
popView.bgClickBlock = ^{
            [weakPopview dismiss];
        };

**Comment by LoSenTrad** [comment]
不太明白 请上一下整个执行弹框的代码

**Comment by Madness66** [comment]
AMKSignInPopView *signInView = [[AMKSignInPopView alloc] initWithFrame:CGRectMake(0, 0, LSTScreenWidth(), LSTScreenHeight())];
我初始化给了全屏frame,把frame设置为内容frame的大小,就解决了,比心!

**Comment by LoSenTrad** [comment]
> ```
> AMKSignInPopView *signInView = [[AMKSignInPopView alloc] initWithFrame:CGRectMake(0, 0, LSTScreenWidth(), LSTScreenHeight())];
> ```
> 
> 我初始化给了全屏frame,把frame设置为内容frame的大小,就解决了,比心!

内部手势确实被拦截了 已经做了优化了
