### ISSUE TITLE
如果只想竖屏不想支持横屏切换是否有参数可以设置？

### ISSUE THREAD

**Issue by Mase9527** [LoSenTrad/LSTPopView#35]
如果只想竖屏不想支持横屏切换是否有参数可以设置？

**Comment by LoSenTrad** [comment]
@LoSenTrad 不是很明白你的意思

**Comment by Mase9527** [comment]
> @LoSenTrad 不是很明白你的意思

就是如果手机开了自动横屏   LSTPopView 也会跟着横屏  我想要LSTPopView 不跟着手机系统横屏， 永远保持竖屏的状态

**Comment by LoSenTrad** [comment]
@LoSenTrad 属性isObserverScreenRotation可以设置不监听横竖屏适应, 默认YES. 你设置成NO即可

**Comment by Mase9527** [comment]
> @LoSenTrad 属性isObserverScreenRotation可以设置不监听横竖屏适应, 默认YES. 你设置成NO即可
好的 谢谢
