### ISSUE TITLE
消失动画的问题

### ISSUE THREAD

**Issue by clearlovelyQ** [LoSenTrad/LSTPopView#38]
点击弹框消失的动画可以自定义嘛，比如我想缩放消失，目前框架提供的只有到顶，左，底，右

**Comment by LoSenTrad** [comment]
@clearlovelyQ 你可以给自己自定义的view 添加点击手势 然后手势出发 消失动画 就可以了

**Comment by clearlovelyQ** [comment]
感谢回复，已解决，不过又发现了一点小问题，xib自定义view的时候，view上的点击事件有延迟，我用你的demo测试，也是有一点延迟，不知道是什么问题，希望能看一下，感谢

**Comment by clearlovelyQ** [comment]
自己验证了一下，不是xib的事情，我pop的动画设置的是LSTPopStyleScale，然后如果popView.popDuration 设置的比较长的话，目前设置的是1；会发现背景view和自定义的view，不是同时出现的，自定义view貌似早出现一点，然后此时如果点击自定义view上的点击事件，确实无法响应。然后，等背景view出现之后，就正常了

**Comment by LoSenTrad** [comment]
@LoSenTrad 好的 哈哈

**Comment by LoSenTrad** [comment]
好的 哈哈

**Comment by clearlovelyQ** [comment]
可以让背景view和自定义的view同时出现吗，测试了下，可能是因为动画的关系，自定义的view确实会出现的晚一点，此时如果快速点击view上的点击事件，确实会延迟。我第一次没找到原因是因为背景view是clearcolor

**Comment by clearlovelyQ** [comment]
https://user-images.githubusercontent.com/26817910/118764939-e2917000-b8ac-11eb-9610-a05f51720225.mp4

**Comment by clearlovelyQ** [comment]
可能我描述的您不是很理解，看上面视频，当我点击cell的时候，背景黑色的出现是有个过程的，而且是晚于pop出来的view的

**Comment by LoSenTrad** [comment]
@LoSenTrad 明白你的意思 自定义view的点击事件 确实是要view全完显示出来才能点击出发的

**Comment by clearlovelyQ** [comment]
好的，那我就把动画时间设置短一点吧 @LoSenTrad
