### ISSUE TITLE
状态栏高度计算有问题，在iPhone12上调试，得出20，应该是47才对。

### ISSUE THREAD

**Issue by HoodL** [LoSenTrad/LSTPopView#39]
CGFloat LSTStatusBarHeight() {
    if (lst_IsIphoneX_ALL()) {
        return 44;
    } else {
        return 20;
    }
}
lst_IsIphoneX_ALL方法里面列出了4种分辨率，只要全屏不等于这4种分辨率就是刘海屏，这种算法有问题吧。

**Comment by LoSenTrad** [comment]
@HoodL LSTCategory分类里面确实没更新 下个版本修复

**Comment by LoSenTrad** [comment]
@HoodL demo pod update即可 你应该是下载到旧版本了
