### ISSUE TITLE
alertView内部有个循环引用的地方

### ISSUE THREAD

**Issue by Oldfishking** [LoSenTrad/LSTPopView#4]
![image](https://user-images.githubusercontent.com/40530760/79191862-24561880-7e5a-11ea-919c-1c0dccdc0007.png)
758行，经测试LSTPopView是没有释放的，作者大大weak改一下下？

**Comment by Oldfishking** [comment]
额图好像挂了，就是LSTAlertView.m文件show方法，第758行那个block，小问题而已

**Comment by Oldfishking** [comment]
抱歉好像不是因为这个。。我再看看

**Comment by LoSenTrad** [comment]
@Oldfishking 用#define LSTPopViewWK(object)  __weak typeof(object) wk_##object = object; 这个快捷宏 弱化一下 
例如: 
``` 
LSTPopView *popView = [LSTPopView initWithCustomView:view popStyle:LSTPopStyleSmoothFromTop dismissStyle:LSTDismissStyleSmoothToBottom];
    popView.hemStyle = LSTHemStyleCenter;
    popView.adjustY = 10;
    popView.isClickFeedback = YES;
    LSTPopViewWK(popView)
    popView.bgClickBlock = ^{
        NSLog(@"点击了背景");
        [wk_popView dismiss];
    };
```

**Comment by LoSenTrad** [comment]
本周会发布新版本.敬请期待 奥利给
