### ISSUE TITLE
有个问题  底部弹出的view中 有个 UITableView 底部有个输入框 当点击输入框的时候 

### ISSUE THREAD

**Issue by twlk-jzy** [LoSenTrad/LSTPopView#49]
有个问题  底部弹出的view中 有个 UITableView 底部有个输入框 当点击输入框的时候  键盘弹出 view会被移动到键盘的上方  但是键盘和view的中间会有一段空白区域 请问这个怎么解决呢  谢谢
![IMG_0384](https://github.com/LoSenTrad/LSTPopView/assets/8147530/afb4f70c-e557-48cb-9633-21be5aaba793)

**Comment by LoSenTrad** [comment]
/** 弹窗和键盘的距离 默认10 */
@property (nonatomic, assign) CGFloat avoidKeyboardSpace;

**Comment by twlk-jzy** [comment]
非常感谢
