### ISSUE TITLE
能否支持弹框自适应高度呢

### ISSUE THREAD

**Issue by H4AER** [LoSenTrad/LSTPopView#8]

**Comment by LoSenTrad** [comment]
@H4AER 如果你要自适应高度,可以自己改变你的自定义view的高度,LSTPopView内部监听了frame,弹框会自动更新frame. 你可以试试.

**Comment by H4AER** [comment]
比如说 我有一个自定义view ，里边只有一个Label，Label我添加了约束，现在我希望Pop能够自适应大小得话，目前只能手动去计算吗

**Comment by LoSenTrad** [comment]
@H4AER 我明白你的意思, 目前没有考虑做自适应高度这个需求,  你可以先计算文本高度,再改变弹框高度即可.  计算文本高度可以用LSTCategory分类里面String分类. 实现起来 也不难

**Comment by H4AER** [comment]
好的，感谢回复
